### ISSUE TITLE
[Feature] Add JUnit XML Report as option

### ISSUE THREAD

**Issue by FilipeGoncalvesBasecone** [MicroFocus/lrc-gh-action#3]
Currently looking at the Readme file of LRC github action the only available report types are: "pdf, csv and docx". 

Would be great to add the option of having a JUnit XML report similar to other LoadRunner Cloud plugins already do (Ex: LRC plugin for AzureDevOps, LRC plugin for Jenkins).

Having a JUnit report would allow the possibility of uploading the report to Xray or similar tools.

**Comment by weisun10** [comment]
@FilipeGoncalvesBasecone, junit xml report is always generated

**Comment by FilipeGoncalvesBasecone** [comment]
Hello @weisun10 

According to the Readme from the Github Action:
![image](https://github.com/MicroFocus/lrc-gh-action/assets/131873731/78eef0b6-267e-4c38-ba7a-46aeee3dd94a)

I don't see junit xml  report on the options.

Best regards,
Filipe

**Comment by weisun10** [comment]
Since junit xml report is **always** generated, no optiion is exposed to control it. You can trigger a job, then locate the file generated in the same folder as other report file(s).

**Comment by FilipeGoncalvesBasecone** [comment]
@weisun10 
I have the option of generating the pdf report and the junit is not generated as per the log of a sample run:
![image](https://github.com/MicroFocus/lrc-gh-action/assets/131873731/85cebf34-2d7b-4a02-acf4-96fa0f24a31f)

So not sure how it is generated automatically as you can see on the screenshot it only downloaded the PDF report no Junit report was downloaded. I even upload the folder content as a Artifact in a next step and I don't see any Junit report when I download it.

If I don't specify a **lrc_report_types** according to the readme it doesn't generate a report apparently
How would to Github Action look like then?
We are invoking it like this:
```
      - name: Run Warm Up Test in LRC
        uses: MicroFocus/lrc-gh-action@v1
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: ${{secrets.LRC_CLIENT_ID}}
          LRC_CLIENT_SECRET: ${{secrets.LRC_CLIENT_SECRET}}
        with:
          lrc_server: 'https://loadrunner-cloud.saas.microfocus.com'
          lrc_tenant: <tenant_id>
          lrc_project: <project_id>
          lrc_test_id: <test_id>
          lrc_output_dir: './lrc_report'
          lrc_report_types: 'pdf'
```
